apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: neo4j-poc
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/launch-stage: BETA # Required for GCS FUSE
    spec:
      serviceAccountName: neo4j-poc-sa@alpfr-splunk-integration.iam.gserviceaccount.com

      containers:
      # 1. Streamlit Application
      - image: us-central1-docker.pkg.dev/alpfr-splunk-integration/neo4j-poc-repo/frontend:20260316-182617
        name: frontend
        ports:
        - containerPort: 8501
        env:
        - name: NEO4J_URI
          value: "bolt://localhost:7687"
        - name: NEO4J_USER
          value: "neo4j"
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: neo4j-password-secret
              key: latest
        resources:
          limits:
            memory: 512Mi
            cpu: 1000m

      # 2. Neo4j Database Sidecar
      - image: neo4j:5.18.0
        name: neo4j-db
        env:
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef:
               name: neo4j-auth-secret
               key: latest
        startupProbe:
          tcpSocket:
            port: 7687
          initialDelaySeconds: 15
          timeoutSeconds: 2
          failureThreshold: 20
          periodSeconds: 5
        resources:
          limits:
            memory: 1Gi
            cpu: 1000m
