apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  labels:
    app: streamlit
spec:
  type: LoadBalancer
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: streamlit
