apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: neo4j-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: neo4j
  updatePolicy:
    updateMode: "Auto"
